package song_charts_2402;

import java.io.BufferedReader;
import java.io.EOFException;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;


public class SongList {
	
	private ArrayList<Song> songs;
	
	public SongList(){
		songs = new ArrayList<Song>();
	}
	
	public ArrayList<Song> getSongs(){ return songs; }
	public void add(Song aSong) {songs.add(aSong);}
	
	public void exportXMLToFile(String indent, PrintWriter outputFile){
		if(songs.isEmpty()) return;
		for(Song song : songs) song.exportXMLToFile(indent, outputFile);
	}
	
	public static SongList parseFromFile(File inputFile){

		
		if(inputFile == null) return null;
		
		SongList theSongs  = new SongList();

		
		BufferedReader inputFileReader;
		
	    String inputLine; //current input line
		try{
			   inputFileReader= new BufferedReader(new FileReader(inputFile));
			    
			   while((inputLine = inputFileReader.readLine()) != null){
				   
				   inputLine = inputLine.trim();
				   
				   //WARNING: this code does not yet validate the XML file
				   //it current ignore the XML tags
				   //<?xml version = "1.0"?>, <fakebookXML>

				   
				   if(inputLine.startsWith(Song.XMLsongStartTag) ){
					   
					   Song song = Song.parseFromFile(inputFileReader);					   
					   if(song != null) theSongs.add(song);
					   
				   }
				   

			   
			   
			   } //end while
			   
			   
		}catch (EOFException e) {
            System.out.println("File Read Error: EOF encountered, file may be corrupted.");
        } catch (IOException e) {
            System.out.println("File Read Error: Cannot read from file.");
        }
		
		
		return theSongs;			
				
	}

	
	/*
	 * This is where all the searching happens.
	 * 
	 * A new list is generated by going through the 'master' list with a filter.
	 * 
	 * If no filter is provided, all songs will be returned.
	 */
	public static SongList searchForSongs(SongList songsToFilterFrom, String songNameFilter){
		if (songNameFilter != null && songNameFilter.length() > 0){
			//New list to return.
			SongList filteredSongs = new SongList();
			
			//Convert the filter to lower-case so we can do a 
			//case insensitive search
			songNameFilter = songNameFilter.toLowerCase();
			
			/*
			 * We want to search for any words the user has entered.
			 * 
			 * We are assuming that words will be delimited by a 
			 * whitespace.
			 */
			String[] wordsToSearchFor = songNameFilter.split(" ");
			
			//Add songs to the list that meet the criteria.
			for(Song song : songsToFilterFrom.getSongs()){
				//Look for each word the user has input
				for (String word: wordsToSearchFor){
					if (song.getTitle().toLowerCase().contains(word)){
						filteredSongs.add(song);
					}
				}
			}

			return filteredSongs;
		}
		else {
			//Return all; no filter was selected
			return songsToFilterFrom;
		}
		
	}

}
